# Generated by Django 6.0.8 on 2026-08-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
                ('phonetic', models.CharField(blank=True, max_length=100)),
                ('pos', models.CharField(blank=True, max_length=50)),
                ('definition', models.TextField()),
                ('level', models.CharField(blank=True, max_length=10)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('examples', models.JSONField(default=list)),
                ('collocations', models.JSONField(default=list)),
                ('synonyms', models.JSONField(default=list)),
                ('antonyms', models.JSONField(default=list)),
                ('mastery', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_word_of_day', models.BooleanField(default=False)),
                ('word_of_day_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['word'],
            },
        ),
    ]
