# Generated by Django 6.0.8 on 2026-08-20 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
                ('phonetic', models.CharField(blank=True, max_length=100)),
                ('pos', models.CharField(blank=True, max_length=50)),
                ('definition', models.TextField()),
                ('level', models.CharField(blank=True, max_length=10)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('examples', models.JSONField(default=list)),
                ('collocations', models.JSONField(default=list)),
                ('synonyms', models.JSONField(default=list)),
                ('antonyms', models.JSONField(default=list)),
                ('mastery', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_word_of_day', models.BooleanField(default=False)),
                ('word_of_day_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastered', models.BooleanField(default=False)),
                ('mastery_level', models.IntegerField(default=0)),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learned_words', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learned_by', to='vocabulary.word')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'word')},
            },
        ),
    ]
