# Generated by Django 6.0.8 on 2026-08-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_userword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='category',
            field=models.CharField(blank=True, choices=[('academic', 'Academic'), ('business', 'Business'), ('daily', 'Daily Use'), ('literature', 'Literature'), ('science', 'Science'), ('technology', 'Technology'), ('arts', 'Arts & Humanities'), ('social', 'Social Sciences'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
