# Generated by Django 6.0.8 on 2026-08-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0003_alter_word_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userword',
            name='reviewed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
