# Generated by Django 6.0.8 on 2026-08-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0004_alter_userword_reviewed_at_alter_word_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userword',
            name='reviewed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
